# Name of the Namespace to use
namespace: mongodb

# OpenShift manages security context on its own
managedSecurityContext: true

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Name of the operator image
  operator_image_name: mongodb-enterprise-operator-ubi

  # Name of the deployment of the operator pod
  deployment_name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator
  version: 1.17.0

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  watchedResources:
  - mongodb
  - opsmanagers
  - mongodbusers

  nodeSelector: {}

  tolerations: []

  affinity: {}

## Database
database:
  name: mongodb-enterprise-database-ubi
  version: 2.0.2

initDatabase:
  name: mongodb-enterprise-init-database-ubi
  version: 1.0.12

## Ops Manager
opsManager:
  name: mongodb-enterprise-ops-manager-ubi

initOpsManager:
  name: mongodb-enterprise-init-ops-manager-ubi
  version: 1.0.9

initAppDb:
  name: mongodb-enterprise-init-appdb-ubi
  version: 1.0.12

agent:
  name: mongodb-agent
  version: 11.12.0.7388-1

mongodb:
  name: mongodb-enterprise-appdb-database-ubi
  repo: quay.io/mongodb


## Registry
registry:
  # The pull secret must be specified
  imagePullSecrets:
  pullPolicy: Always
  operator: quay.io/mongodb
  database: quay.io/mongodb
  initDatabase: quay.io/mongodb
  initOpsManager: quay.io/mongodb
  opsManager: quay.io/mongodb
  initAppDb: quay.io/mongodb
  appDb: quay.io/mongodb
  agent: quay.io/mongodb


# Set this to false to disable subresource utilization
# It might be required on some versions of Openshift
subresourceEnabled: true
